### ISSUE TITLE
Always crashes when app was in background

### ISSUE THREAD

**Issue by Ol-li** [thebigg73/OpenSongTablet#254]
I get this error and have to restart the app.

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean q3.g.p()' on a null object reference
	at com.garethevans.church.opensongtablet.MainActivity.p5(SourceFile:129)
	at com.garethevans.church.opensongtablet.MainActivity.Q4(SourceFile:1)
	at s2.n.run(SourceFile:1)
	at android.app.Activity.runOnUiThread(Activity.java:7514)
	at com.garethevans.church.opensongtablet.MainActivity.B2(SourceFile:6)
	at com.garethevans.church.opensongtablet.performance.PerformanceFragment.J0(SourceFile:86)
	at androidx.fragment.app.Fragment.n1(SourceFile:25)
	at androidx.fragment.app.l0.f(SourceFile:209)
	at androidx.fragment.app.l0.m(SourceFile:128)
	at androidx.fragment.app.m0.t(SourceFile:31)
	at androidx.fragment.app.e0.b1(SourceFile:28)
	at androidx.fragment.app.e0.T(SourceFile:10)
	at androidx.fragment.app.e0.V(SourceFile:2)
	at androidx.fragment.app.Fragment.F1(SourceFile:20)
	at androidx.fragment.app.l0.f(SourceFile:314)
	at androidx.fragment.app.l0.m(SourceFile:128)
	at androidx.fragment.app.m0.t(SourceFile:31)
	at androidx.fragment.app.e0.b1(SourceFile:28)
	at androidx.fragment.app.e0.T(SourceFile:10)
	at androidx.fragment.app.e0.y(SourceFile:12)
	at androidx.fragment.app.u.c(SourceFile:5)
	at androidx.fragment.app.r.onStart(SourceFile:21)
	at androidx.appcompat.app.d.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1566)
	at android.app.Activity.performStart(Activity.java:8572)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3934)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by thebigg73** [comment]
Thanks for submitting this.  Unfortunately this is obsfucated code as a result of how I uploaded the last update meaning it isn't easy to track the issue.  v6.0.1 has been uploaded and isn't obsfucated.  It has some bug fixes, but I doubt it will sort your issue.  If it happens again, can you post the relevant code (it should have line numbers with readable function names rather that 'sourcefile').  Thanks for taking the time to help me fix bugs in the app

**Comment by Ol-li** [comment]
It seems to be OK now with the newer version
