### ISSUE TITLE
Can't get past the first-time setup screen (Android 6 related?)

### ISSUE THREAD

**Issue by joonty** [thebigg73/OpenSongTablet#8]
Hi, I've been using OpenSong Tablet for a while now, and absolutely love it! Thanks for all your work.

However, I came to open it today on my Google Nexus 7 and was hit with the first-time setup screen screen, which is strange because I'd set it up months ago. Not only that, but choosing any of the options did nothing - it just went straight back to the same screen.

I think it's related to my upgrade to Android 6, because it's the only thing that's really changed since I last used it.

I do some Android dev too, so I'm going to take a look and see what I can find. If I get anywhere I'll open a PR, but I just wanted to raise this here in case you found a fix first.

Thanks

**Comment by joonty** [comment]
A bit more on this. Opening the app on Android 6 gives the following error (before the first time setup screen):

```
11-15 11:42:59.588  21302-21302/com.garethevans.church.opensongtablet E/tag﹕ Failed to copy asset file: Love everlasting
    java.io.FileNotFoundException: /storage/emulated/0/documents/OpenSong/Songs/Love everlasting: open failed: EACCES (Permission denied)
            at libcore.io.IoBridge.open(IoBridge.java:452)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
            at com.garethevans.church.opensongtablet.SettingsActivity.onCreate(SettingsActivity.java:344)
            at android.app.Activity.performCreate(Activity.java:6237)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
            at libcore.io.Posix.open(Native Method)
            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
            at libcore.io.IoBridge.open(IoBridge.java:438)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
            at com.garethevans.church.opensongtablet.SettingsActivity.onCreate(SettingsActivity.java:344)
            at android.app.Activity.performCreate(Activity.java:6237)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

If you ask it to copy the default songs, you get similar errors relating to file system permissions:

```
11-15 11:44:46.772  21302-22051/? E/tag﹕ Failed to copy asset file: From heaven You came
    java.io.FileNotFoundException: /storage/emulated/0/documents/OpenSong/Songs/From heaven You came: open failed: EACCES (Permission denied)
            at libcore.io.IoBridge.open(IoBridge.java:452)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
            at com.garethevans.church.opensongtablet.StorageChooser$CopyAssetsTask.doInBackground(StorageChooser.java:419)
            at com.garethevans.church.opensongtablet.StorageChooser$CopyAssetsTask.doInBackground(StorageChooser.java:362)
            at android.os.AsyncTask$2.call(AsyncTask.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
            at libcore.io.Posix.open(Native Method)
            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
            at libcore.io.IoBridge.open(IoBridge.java:438)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
            at com.garethevans.church.opensongtablet.StorageChooser$CopyAssetsTask.doInBackground(StorageChooser.java:419)
            at com.garethevans.church.opensongtablet.StorageChooser$CopyAssetsTask.doInBackground(StorageChooser.java:362)
            at android.os.AsyncTask$2.call(AsyncTask.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
11-15 11:44:46.774  21302-22051/? E/tag﹕ Failed to copy asset file: From the sleep of ages
    java.io.FileNotFoundException: /storage/emulated/0/documents/OpenSong/Songs/From the sleep of ages: open failed: EACCES (Permission denied)
            at libcore.io.IoBridge.open(IoBridge.java:452)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
            at com.garethevans.church.opensongtablet.StorageChooser$CopyAssetsTask.doInBackground(StorageChooser.java:419)
            at com.garethevans.church.opensongtablet.StorageChooser$CopyAssetsTask.doInBackground(StorageChooser.java:362)
            at android.os.AsyncTask$2.call(AsyncTask.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
            at libcore.io.Posix.open(Native Method)
            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
            at libcore.io.IoBridge.open(IoBridge.java:438)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
            at com.garethevans.church.opensongtablet.StorageChooser$CopyAssetsTask.doInBackground(StorageChooser.java:419)
            at com.garethevans.church.opensongtablet.StorageChooser$CopyAssetsTask.doInBackground(StorageChooser.java:362)
            at android.os.AsyncTask$2.call(AsyncTask.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
```

And so on, continuously! I'll see if I can get any time over the coming week to take a look.

I also had issues compiling everything for the first time, due to missing drawables. In the end I went through and replaced the missing ones with roughly equivalent ones, but it would obviously be good to get the originals! I've pasted the error log [here](https://gist.github.com/joonty/f3bd735b0a2f19e6ee81).

**Comment by thebigg73** [comment]
Hi Jonathan,

I'll try to 'borrow' my wife's phone (the only device in the house running
marshmallow) and see if I can replicate the error.

Thanks for offering to help!

Gareth

**Comment by thebigg73** [comment]
Hi Jonathan,

I found the problem!  Marshmallow seeks to ask for permission to use the
storage on your device.  For some reason, the permission isn't being
sought.  This is why the device can't copy the songs, or run any of the
songs.
A temporary fix is to go to your system settings, choose Apps and select
OpenSong Tablet.  In the app settings, click on permissions and switch on
storage.

I'll look into fixing the issue properly later this week.  I'll also make
sure all the drawable resources are uploaded to github.

Cheers,
Gareth

**Comment by joonty** [comment]
That's great! Thanks for being so quick on this, it's very appreciated.

Cheers, Jon
