### ISSUE TITLE
Crash on Fire HD 10 7th Generation at 5.2.4 (5.2.3 opens)

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#89]
Hello Gareth,

I wanted to update a friends Fire HD 10 7th Generation to 5.2.4 and did.  On open it immediately closes. A download of 5.2.3 once manually installed would open - this suggests a change in 5.2.4 is resulting in problems.  I can see cast, media and presentation changes.  As the Fire HD 10 does not support cast my thinking is cast changes are the first to eliminate.

Other things noticed:
The font picker does not work (reports failed fonts) in the app (going back to 5.1.4 it was still broken).

_EDIT - Research fond others reporting Google drive does not work on Fire HD 10_ 
Google drive does not work on stock Fire HD 10. I could not download the historic apps from your sites google drive.  This may hinder others trying to isolate the problem.  Tried this with the stock Amazon browser and (After side loading) Chrome - no joy

These feel like problems caused by Amazons android fork.  Hopefully work around is possible as we are using 3 Fire HD 10 in my wider group!

My own Fire HD 10 7th gen is running Lineage OS Based on Android 5.1 and is working - this does cast and do all things correctly at 5.2.4.  I must give the stock HD 10 back on Sunday (and I can't fiddle too much with it) so I am not sure I can help much further!  At this point others in my team will auto update and break.

Apologies for splitting the conversation!

Kind regards
Ian

**Comment by thebigg73** [comment]
Hi Ian,

I didn't know about the cast feature non existing on the fire 10.  There
are a few users contacting me, bit like you I don't have a fire 10.  The
lack of cast shouldn't cause a crash as it only turns on if the device has
the feature, it isn't required.
One user got back to me and said that installing the Google play store on
their device and installing the app from there sorted it.

Did you install from the Amazon app store or via Android studio?  If you
have the device, can you capture the logcat crash report - that will
identify the issue.  The Amazon app store does not collect crash reports
unlike the Google play store.

Gareth

**Comment by thebigg73** [comment]
I'm aware of the fonts - that is an Amazon Vs Google thing.  I'm looking at
an alternative in the big update I'm working on

**Comment by iv-gha** [comment]
Hello Gareth,

I attach the tail of a logcat - is this useful?

I found installing opensource play equivalent MicroG helps the browsers ability to download from gdrive - but this does not cure the 5.2.4 crash.  MIcroG give access to googles account mechanisms etc.

I think it points to the lack of google play services, which is not on stock Fire HD 10 android at all.  Nearby connect is not working either (5.2.3) - perhaps this too is depending on play services.  The fact 5.2.4 opens after a user installed play services is a strong indicator of dependancy.

Hopefully useful info.

KInd regards
Ian   

    --------- beginning of main
2020-10-16 09:26:42.882 1919-2696/system_process D/WifiStateMachine: NETWORK_STATUS_UNWANTED_VALIDATION_FAILED
2020-10-16 09:26:42.884 1919-8434/system_process D/WifiNetworkHistory: saving network history: "AndroidWifi"NONE gw: null Network Selection-status: NETWORK_SELECTION_ENABLED ephemeral=false choice:null link:0 status:0 nid:0 hasEverConnected: true
2020-10-16 09:26:42.884 1919-8434/system_process V/WifiNetworkHistory: writeKnownNetworkHistory write config "AndroidWifi"NONE
2020-10-16 09:28:12.437 2779-8265/com.google.android.gms.persistent I/NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.checkin.EventLogService started execution. cause:4 exec_start_elapsed_seconds: 16693 [CONTEXT service_id=218 ]
2020-10-16 09:28:12.452 3460-4095/com.google.android.gms I/Checkin: [EventLogChimeraService] Opted in for usage reporting: false
2020-10-16 09:28:12.452 3460-4095/com.google.android.gms I/Checkin: [EventLogChimeraService] Aggregate from 1602806911426 (log), 1602806911426 (data)
2020-10-16 09:28:12.636 2779-3708/com.google.android.gms.persistent I/NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.checkin.EventLogService finished executing. cause:4 result: 1 elapsed_millis: 228 uptime_millis: 228 exec_start_elapsed_seconds: 16693 [CONTEXT service_id=218 ]
2020-10-16 09:28:12.748 2779-8265/com.google.android.gms.persistent I/NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.clearcut.uploader.QosUploaderService started execution. cause:5 exec_start_elapsed_seconds: 16693 [CONTEXT service_id=218 ]
2020-10-16 09:28:12.768 2779-8265/com.google.android.gms.persistent I/NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.auth.account.be.legacy.AuthCronService started execution. cause:5 exec_start_elapsed_seconds: 16693 [CONTEXT service_id=218 ]
2020-10-16 09:28:12.834 2779-8265/com.google.android.gms.persistent I/NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.clearcut.uploader.QosUploaderService finished executing. cause:5 result: 1 elapsed_millis: 152 uptime_millis: 152 exec_start_elapsed_seconds: 16693 [CONTEXT service_id=218 ]
2020-10-16 09:28:12.954 2779-3708/com.google.android.gms.persistent I/NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.security.snet.SnetNormalTaskService started execution. cause:5 exec_start_elapsed_seconds: 16693 [CONTEXT service_id=218 ]
2020-10-16 09:28:12.974 2779-8156/com.google.android.gms.persistent I/NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.security.snet.SnetNormalTaskService finished executing. cause:5 result: 1 elapsed_millis: 57 uptime_millis: 57 exec_start_elapsed_seconds: 16693 [CONTEXT service_id=218 ]
2020-10-16 09:28:39.599 1919-2702/system_process D/ConnectivityService: NetworkAgentInfo [MOBILE (LTE) - 102] validation failed
2020-10-16 09:28:42.880 2779-3787/com.google.android.gms.persistent W/MessengerIpcClient: Timing out request: 1
2020-10-16 09:28:42.881 2779-3693/com.google.android.gms.persistent W/GLSUser: [AppCertManager] Failed to get security token.
    java.io.IOException: SERVICE_NOT_AVAILABLE
        at adiw.b(:com.google.android.gms@202414022@20.24.14 (040700-319035315):19)
        at adiw.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):18)
        at adiw.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):11)
        at hwy.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):17)
        at hww.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):45)
        at hwr.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):0)
        at hwu.a(:com.google.android.gms@202414022@20.24.14 (040700-319035315):10)
        at gbi.call(:com.google.android.gms@202414022@20.24.14 (040700-319035315):0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at soy.b(:com.google.android.gms@202414022@20.24.14 (040700-319035315):12)
        at soy.run(:com.google.android.gms@202414022@20.24.14 (040700-319035315):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at sux.run(:com.google.android.gms@202414022@20.24.14 (040700-319035315):0)
        at java.lang.Thread.run(Thread.java:761)
2020-10-16 09:28:52.819 2779-8156/com.google.android.gms.persistent I/NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.auth.account.be.legacy.AuthCronService finished executing. cause:5 result: 3 elapsed_millis: 40085 uptime_millis: 40085 exec_start_elapsed_seconds: 16693 [CONTEXT service_id=218 ]
2020-10-16 09:28:52.960 2779-2779/com.google.android.gms.persistent W/MessengerIpcClient: Received response for unknown request: 1
2020-10-16 09:29:22.957 2779-3693/com.google.android.gms.persistent W/GLSUser: [AppCertManager] IOException while requesting key: 
2020-10-16 09:29:57.842 2779-3693/com.google.android.gms.persistent E/WakeLock: GCM_CONN_ALARM ** IS FORCE-RELEASED ON TIMEOUT **

**Comment by iv-gha** [comment]
Hello Gareth,

At the mo.... Install of 
com.google.gsf.login
com.google.android.gsf
com.google.android.gms (so with google settings app)
CHANGED - com.android.vending (with play store app - but not configured - is needed for nearby)
After installing app from Amazon app store (so Amazon handles updating etc)

- fixes 5.2.4 load, nearby connect and fonts. Appears there are a lot of dependencies on 'gms'.

ADDED - Cast icon also appears. Whilst it lists my chromecast it does not connect.  Other apps see both my Fire TV and Chromecast, with chromecast working for cast (not screen share).  The fire HD 10 does not have a cast settings menu to test screen share(!).  A bit rambly - sorry.  I suggest that we may need an option to turn chromecast icon off - for devices where it does not work.

We need to  stop the crash to give stock Amazon users back their songbook.  Perhaps they never had nearby connect or cast working?

Detailing that installing play gets things working but that this is 'at your own risk' - you do not want come back -  might help those willing to fiddle.

Kind regards
Ian

**Comment by thebigg73** [comment]
Excellent detective work!!!
I reset my fire 7 tablet (as I had put Google play services/store on it) and I can now replicate the crash (it was working fine before this).  I'll see what I can see!

**Comment by thebigg73** [comment]
Ok, I've fixed the crash - it was the initialisation of the mCastContext, so I've wrapped that in a try-catch.  It just means that cast won't work or Nearby connections.  I'm thinking show a snackbar message about the issue with a link to a guide on how to install the extra services if users want to use cast/nearby connections/fonts.

**Comment by iv-gha** [comment]
Sounds good.  The font stuff, as you indicate, does needs to work without the user needing gms.  This would preserve songbook use for all without gms fiddling.

You might like to consider how many places a useful messages needs to appear - perhaps a bigger thing (with link to your site?) on the initial screen, a fix for font error(s) into makng silent use of Lato and stopping ability to adjust, and perhaps a toast on use of nearby with a block on further action.  I guess the cast icon will simply not appear.

The Fire tablets are often very cheap and are readily available here and abroad! I for one need them to 'mostly' work!

Thanks for the good work.

Kind regards
Ian

p.s. I put up a pull for presentation mode alert handling - fun

**Comment by iv-gha** [comment]
I have found that installing full Play gms and MicroG using the Vanced installer (no need for Vanced itself and this app keeps microG up-to-date which is the plus) gives working Cast!  Who knew.

**Comment by thebigg73** [comment]
Yeah,
Got a fix pushed up to master.  It disables the Google Cast/Fonts/Connect features and gives subtle warnings with info about how to fix it via a link to my site (still to finish updating that as well!).
Now to pull in your update!

Happy days!
Gareth

**Comment by iv-gha** [comment]
Just a thought, whilst this is Fire related the 'case' is any Android 5+ device without Google play - though the later is generally caused by an advanced user who is willing to fix things.  Amazon are the only commercial fork of Android, I can think of, in wide use - to the point where the manufacturer of Amazon devices is prohibited from making Google approved devices!  There may be further Chinese forks in the future - Trump's ban is making Huawei think hard.  Perhaps add 'Taking a similar approach for other devices without Google play services may help.'.
